Repository yoonjoonseok/OLOL_service, pull requests merged in 2023-07, with the labels that each got.

#173 아이콘 적용, 창이 여러 개일때 푸시 알림 여러 개 오는 문제 해결, 참가된 공고에 참가자 왔을 시 알림
  src/main/java/com/ll/olol/boundedContext/notification/eventListener/NotificationEventListener.java
  src/main/resources/static/firebase-messaging-sw.js
  src/main/resources/static/resource/common/icon/favicon.ico
  src/main/resources/static/resource/common/icon/olol.png
  src/main/resources/static/sse-messaging-sw.js
  src/main/resources/templates/common/layout.html
Labels: enhancement, fix

#168 feat: 채팅 기능 구현
  .DS_Store
  build.gradle
  src/main/java/com/ll/olol/base/entity/BaseEntity.java
  src/main/java/com/ll/olol/base/webSocket/WebSocketConfig.java
  src/main/java/com/ll/olol/boundedContext/chat/controller/ChatController.java
  src/main/java/com/ll/olol/boundedContext/chat/controller/MessageController.java
  src/main/java/com/ll/olol/boundedContext/chat/dto/ChatMessageDTO.java
  src/main/java/com/ll/olol/boundedContext/chat/dto/ChatRoomDetailDTO.java
  src/main/java/com/ll/olol/boundedContext/chat/entity/ChatMessage.java
  src/main/java/com/ll/olol/boundedContext/chat/entity/ChatRoom.java
  src/main/java/com/ll/olol/boundedContext/chat/repository/ChatMessageRepository.java
  src/main/java/com/ll/olol/boundedContext/chat/repository/ChatRoomRepository.java
  src/main/java/com/ll/olol/boundedContext/chat/service/ChatService.java
  src/main/java/com/ll/olol/boundedContext/member/entity/Member.java
  src/main/java/com/ll/olol/boundedContext/member/repository/MemberRepository.java
  src/main/java/com/ll/olol/boundedContext/member/service/MemberService.java
  src/main/resources/templates/usr/chat/chatList.html
  src/main/resources/templates/usr/chat/room.html
  src/main/resources/templates/usr/layout/layout.html
Labels: enhancement, style

#186 알림 수신 설정 기능, 리팩토링, UI 변경
  src/main/java/com/ll/olol/boundedContext/member/controller/MemberController.java
  src/main/java/com/ll/olol/boundedContext/member/entity/Member.java
  src/main/java/com/ll/olol/boundedContext/notification/controller/NotificationController.java
  src/main/java/com/ll/olol/boundedContext/notification/eventListener/NotificationEventListener.java
  src/main/java/com/ll/olol/boundedContext/notification/repository/NotificationRepository.java
  src/main/java/com/ll/olol/boundedContext/notification/service/NotificationService.java
  src/main/java/com/ll/olol/boundedContext/recruitment/controller/RecruitmentPeopleController.java
  src/main/java/com/ll/olol/boundedContext/recruitment/repository/LikeableRecruitmentArticleRepository.java
  src/main/java/com/ll/olol/boundedContext/recruitment/repository/RecruitmentPeopleRepository.java
  src/main/java/com/ll/olol/boundedContext/recruitment/repository/RecruitmentRepository.java
  src/main/java/com/ll/olol/boundedContext/recruitment/service/LikeableRecruitmentArticleService.java
  src/main/java/com/ll/olol/boundedContext/recruitment/service/RecruitmentPeopleService.java
  src/main/java/com/ll/olol/boundedContext/recruitment/service/RecruitmentService.java
  src/main/resources/application.yml
  src/main/resources/templates/usr/chat/room.html
  src/main/resources/templates/usr/layout/myPage.html
  src/main/resources/templates/usr/member/attendList.html
  src/main/resources/templates/usr/member/fromAttendList.html
  src/main/resources/templates/usr/notification/list.html
Labels: enhancement
